name: ICLx Check PR
# garantees runnability and runs tests

on:
  workflow_dispatch: 
    inputs: 
      target: 
        
  pull_request:
     types:
     - opened
     - synchronize
     - reopened
     - closed

jobs:
  Test:
     if: ${{ github.event.action != 'closed' || github.event.pull_request.merged == true }}
     runs-on: [ ubuntu-latest ]
     steps:
     #- name: Checkout
     #  run: actions/checkout@v3 
     - run: |
         echo 'Test!'

  deploy:
    depends_on: Test
    environment: DUMMY
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: |
          echo "Deploying to"
             
